name: Checks

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # At 16:00 on Wednesday
    - cron: "0 16 * * 3"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: 2.3.0
      - uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: 0.9.1

      - run: snforge test
