name: Checks

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # At 16:00 on Wednesday
    - cron: "0 16 * * 3"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get scarb version
        id: extractScarbVersion
        run: |
          curl -s https://api.github.com/repos/foundry-rs/starknet-foundry/releases/latest | grep tarball_url | cut -d '"' -f 4 | xargs -n 1 curl -L -o latest.tar.gz
          mkdir latest
          tar -xz --strip-components=1 -C latest -f latest.tar.gz
          version=$(grep scarb latest/.tool-versions | awk '{print $2}')
          
          echo "scarbVersion=$version" >> "$GITHUB_OUTPUT"

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ steps.extractScarbVersion.outputs.scarbVersion }}
      - uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: latest

      - run: snforge test
